version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - aws cloudformation package --template-file template.yaml --s3-bucket artifacts-dev-12 --output-template-file package.yaml

  artifacts:
 files:
   - package.yml
   - "**.*"
