AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  NextJsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: NextJsFunction
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: ./
      MemorySize: 1024
      Timeout: 30
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: API endpoint URL for the Next.js app
    Value:
      Fn::Sub: 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
