AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple nodejs lambda function
Resources:
  MyLambdaFunctoin:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      FunctionName: MyLambdaFunctoin
      CodeUri: ./src
